export enum Roles {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER'
}

export enum Task_Types {
  PROGRAMMING = 'PROGRAMMING',
  LEADERSHIP = 'LEADERSHIP',
  COMMUNICATION = 'COMMUNICATION'
}

export enum TaskStatus {
  OPEN = 'OPEN',
  UPLOADING = 'UPLOADING',
  SUBMITTED = 'SUBMITTED'
}
